galaxy_info:
  author: Mario Rodríguez
  description: install docker-ce from docker.com
  company: Beeva
  license: Apache
  min_ansible_version: 2.1
  platforms:
  - name: Ubuntu
    versions:
    - xenial
  - name: Debian
    versions:
    - jessie

  galaxy_tags: []

dependencies: []

